import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import datetime
import requests

# --- 1. إعدادات الصفحة ---
st.set_page_config(page_title="منصة م. مجاهد لمراقبة المعدات", page_icon="⚙️", layout="wide")

# --- 2. إدارة سجل الأحداث (Session State) ---
# هذا الجزء يقوم بتخزين العمليات التي تتم خلال الجلسة
if 'event_log' not in st.session_state:
    st.session_state.event_log = []

# --- 3. إعدادات الربط والتنبيهات ---
TELEGRAM_TOKEN = "8050369942:AAEN-n0Qn-kAmu_9k-lqZ9Fe-tsAOSd44OA"
CHAT_ID = "6241195886"

def send_intelligent_alert(factory_name, machine_name, vibration, status, fault_type):
    now = datetime.datetime.now().strftime("%H:%M - %Y/%m/%d")
    message = (
        f"🏢 **منشأة: {factory_name}**\n"
        f"🚨 **نظام المهندس مجاهد الذكي**\n\n"
        f"📅 الوقت: {now}\n"
        f"⚙️ المعدة: {machine_name}\n"
        f"📊 الاهتزاز: {vibration} mm/s\n"
        f"⚠️ الحالة: {status}\n"
        f"🔍 التشخيص: {fault_type}"
    )
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage?chat_id={CHAT_ID}&text={message}&parse_mode=Markdown"
    try: 
        requests.get(url)
        # إضافة العملية إلى السجل
        st.session_state.event_log.insert(0, {
            "الوقت": now,
            "المنشأة": factory_name,
            "المعدة": machine_name,
            "الحالة": status,
            "التشخيص": fault_type
        })
    except: pass

# --- 4. محرك التحليل التنبؤي ---
def predict_failure_date(vibration):
    days_left = max(1, int(150 / (vibration + 0.1)))
    fail_date = datetime.date.today() + datetime.timedelta(days=days_left)
    return days_left, fail_date

# --- 5. دالة التقرير المطور ---
def generate_pro_report(factory, machine, vibration, status, fault, temp, days, f_date):
    report = f"""
    ==========================================
    TECHNICAL INSPECTION REPORT - PRO VERSION
    ==========================================
    Engineer: Mogahed Bashir Ahmed
    Date: {datetime.date.today()}
    
    [FACILITY INFO]
    - Location: {factory}
    - Asset ID: {machine}
    
    [LIVE MEASUREMENTS]
    - Vibration: {vibration} mm/s
    - Bearing Temperature: {temp} C
    
    [DIAGNOSTIC RESULTS]
    - Health Status: {status}
    - Identified Fault: {fault}
    
    [PREDICTIVE MAINTENANCE]
    - Estimated Remaining Life: {days} Days
    - Predicted Maintenance Date: {f_date}
    ------------------------------------------
    Generated by Mogahed Smart AI Platform
    """
    return report

# --- 6. خوارزمية التشخيص ---
def diagnose_fault(vibration):
    if vibration > 7.1: return "Critical: Bearing Failure"
    elif vibration > 4.5: return "Warning: Misalignment"
    return "Normal: Operating within ISO limits"

# --- 7. القائمة الجانبية ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/6840/6840478.png", width=80)
    st.title("👤 الملف المهني")
    st.markdown("### **المهندس مجاهد بشير**")
    st.info("📍 المدينة المنورة، السعودية")
    st.success("✅ **متاح للتوظيف فوراً**")
    st.write("📞 `+966501318054` ")
    
    linkedin_url = "https://www.linkedin.com/in/mogahed-bashir-52a5072ba/"
    st.markdown(f"""<a href="{linkedin_url}" target="_blank"><img src="https://img.shields.io/badge/LinkedIn-Profile-blue?style=for-the-badge&logo=linkedin" width="100%"></a>""", unsafe_allow_html=True)
    
    st.divider()
    st.header("🏢 إدارة المنشآت")
    selected_factory = st.selectbox("اختر المنشأة:", ["Madinah Factory", "Jeddah Plant", "Yanbu Industrial"])
    machine_selected = st.selectbox("اختر المعدة:", ["Pump P-01", "Fan F-05", "Compressor C-10"])
    vibration_val = st.slider("الاهتزاز (mm/s)", 0.0, 15.0, 3.2)
    temp_val = st.number_input("الحرارة (°C)", value=55)


# --- 8. الواجهة الرئيسية (القسم الترويجي المطور) ---
st.markdown("""
    <div style="background-color:#001529; padding:30px; border-radius:15px; border-right: 10px solid #FFD700; text-align: right; direction: rtl; box-shadow: 0px 4px 15px rgba(0,0,0,0.3);">
        <h1 style="color:white; margin:0; font-family: 'Cairo', sans-serif;">🛡️ منصة م. مجاهد للتحول الرقمي الصناعي</h1>
        <p style="color:#FFD700; font-size:20px; font-weight:bold; margin-top:10px;">نحو صيانة ذكية.. صفر توقف مفاجئ!</p>
        <p style="color:#d9d9d9; font-size:16px; line-height:1.6;">
            هل تعاني من توقف الإنتاج المتكرر؟ نظامنا المدعوم بالذكاء الاصطناعي يمنحك السيطرة الكاملة على أصولك الميكانيكية:
            <br>✅ <b>تنبؤ مبكر:</b> كشف الأعطال قبل وقوعها بأسابيع.
            <br>✅ <b>خفض التكاليف:</b> تقليل نفقات الصيانة الطارئة بنسبة تصل إلى 30%.
            <br>✅ <b>ربط لحظي:</b> إشعارات مباشرة لجوال المهندس المسؤول لضمان سرعة الاستجابة.
        </p>
        <hr style="border-color: #334155;">
        <p style="color:white; font-size:14px;">🛠️ <i>صمم هذا النظام بواسطة خبير الصيانة الميكانيكية م. مجاهد بشير لخدمة رؤية السعودية 2030 في توطين التقنيات الصناعية.</i></p>
    </div>
    """, unsafe_allow_html=True)

st.write("") # مسافة جمالية
st.divider()
st.subheader("📝 سجل أحداث الصيانة الأخير (Maintenance Log)")
if st.session_state.event_log:
    df_log = pd.DataFrame(st.session_state.event_log)
    st.table(df_log)
else:
    st.info("لا توجد أحداث مسجلة حالياً. قم بإرسال تنبيه لتفعيل السجل.")

st.sidebar.caption("تم التطوير بواسطة م. مجاهد بشير - 2026")

